import * as fs from 'fs';
import * as path from 'path';
import { DOCUMENT_ID_RE, documentHtmlPath } from '../htmlDocument';
import { ensureDir, reviewPaths } from '../paths';
import { writeAssets } from '../render';
import { clearFinished, mutateDocumentIndex, nowIso } from '../store';
import { HtmlDocumentMeta } from '../types';

// Keep published documents (and thus the iframe payload) bounded.
const MAX_HTML_BYTES = 5 * 1024 * 1024;

export interface PublishHtmlOptions {
  input?: string;
  documentId?: string;
  title?: string;
  cwd?: string;
}

// Best-effort <title> extraction for a first publish without --title.
function htmlTitle(html: string): string | null {
  const m = /<title[^>]*>([^<]*)<\/title>/i.exec(html);
  const t = m ? m[1].trim() : '';
  return t || null;
}

// Reuse the running server's port (when it serves this project) so the output
// can carry a ready-to-open URL.
function serverUrl(serverJson: string, cwd: string, id: string): string | null {
  try {
    const raw = JSON.parse(fs.readFileSync(serverJson, 'utf8')) as {
      port?: number;
      projectDir?: string;
    };
    if (typeof raw.port !== 'number' || raw.projectDir !== cwd) return null;
    return `http://localhost:${raw.port}/doc/${encodeURIComponent(id)}`;
  } catch {
    return null;
  }
}

export function publishHtml(opts: PublishHtmlOptions = {}): void {
  const cwd = opts.cwd ?? process.cwd();
  if (!opts.input) {
    throw new Error('--input <path> を指定してください');
  }
  const id = opts.documentId;
  if (!id || !DOCUMENT_ID_RE.test(id)) {
    throw new Error(
      '--document-id には英数字で始まる 64 文字以内のスラッグ（[A-Za-z0-9._-]）を指定してください'
    );
  }

  const inputPath = path.resolve(cwd, opts.input);
  const stat = fs.statSync(inputPath);
  if (!stat.isFile()) throw new Error(`ファイルではありません: ${inputPath}`);
  if (stat.size > MAX_HTML_BYTES) {
    throw new Error(`HTML が大きすぎます（最大 ${MAX_HTML_BYTES / 1024 / 1024}MB）: ${inputPath}`);
  }
  // Stored verbatim: the browser renders it in an iframe whose response
  // carries a no-script CSP (see server.ts), which is what keeps scripts from
  // running and blocks external requests. The document is generated by the
  // user's own agent, so there is no untrusted-source threat to strip for.
  const html = fs.readFileSync(inputPath, 'utf8');

  const paths = reviewPaths(cwd);
  ensureDir(paths.dir);
  ensureDir(paths.branchDir);
  ensureDir(paths.documentsDir);
  // Same bootstrap as `generate`: publish-html may be the first command of an
  // HTML-only review, so the self-ignore and client assets must exist, and a
  // leftover finished marker must not stop wait-comments.
  fs.writeFileSync(path.join(paths.dir, '.gitignore'), '*\n');
  writeAssets(paths);
  clearFinished(paths.finished);

  // Body first, index second: a bumped revision (what the browser reloads on)
  // must always point at the new content, never at a stale file.
  fs.writeFileSync(documentHtmlPath(paths, id), html);

  const meta = mutateDocumentIndex(paths.documentsIndex, (index): HtmlDocumentMeta => {
    const now = nowIso();
    const existing = index.documents.find((d) => d.id === id);
    if (existing) {
      existing.revision += 1;
      existing.updatedAt = now;
      if (opts.title) existing.title = opts.title;
      return existing;
    }
    const created: HtmlDocumentMeta = {
      id,
      title: opts.title ?? htmlTitle(html) ?? id,
      revision: 1,
      createdAt: now,
      updatedAt: now,
    };
    index.documents.push(created);
    return created;
  });

  console.log(
    JSON.stringify(
      {
        status: 'published',
        documentId: meta.id,
        title: meta.title,
        revision: meta.revision,
        htmlFile: documentHtmlPath(paths, id),
        url: serverUrl(paths.serverJson, cwd, id),
      },
      null,
      2
    )
  );
}
